import { Component, h } from '@stencil/core';

@Component({
  tag: 'app-root',
  styleUrl: 'app-root.scss',
  shadow: true,
})
export class AppRoot {
  render() {
    return (
      <div class="root">
        <div class="bg-animation">
        <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
          <div id="stars">x</div>
          <div id="stars2">o</div>
          <div id="stars3">x</div>
          <div id="stars4">o</div>
        </div>
        <main>
          <app-home></app-home>
        </main>
      </div>
    );
  }
}
